package com.example.gigify.Navigation

const val ROUTE_SPLASH = "splash"
const val ROUTE_LOGIN = "login"
const val ROUTE_REGISTER = "register"
const val ROUTE_HOME = "home"
const val ROUTE_POST_JOB = "post_job"
const val ROUTE_JOB_DETAIL = "job_detail"
const val ROUTE_MY_JOBS = "my_jobs"
const val ROUTE_CHAT = "chat"
const val ROUTE_CHAT_LIST = "chat_list"
const val ROUTE_PAYMENT = "payment"
const val ROUTE_PAYMENT_METHOD = "payment_method"
const val ROUTE_CLIENT_DASHBOARD = "client_dashboard"
const val ROUTE_WORKER_DASHBOARD = "worker_dashboard"
const val ROUTE_VIEW_WORKER = "view_worker"
const val ROUTE_EDIT_PROFILE = "edit_profile"
const val ROUTE_UPDATE_JOB_STATUS = "update_job_status"
const val ROUTE_NOTIFICATIONS = "notifications"
